### PR TITLE
Issue #55 - handle failures if FFMPEG is not installed

### LINKED ISSUE #55: spec failure if FFMPEG is not installed
Specs are not passing with this failure

```shell
  1) Immagine::Service video thumbnails when the file exists returns a thumbnail for the video
     Failure/Error: FileUtils.cp output_file, File.join(Immagine.settings.lookup('source_folder'), dir, "#{filename}.jpg")

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - ./test-data/src/tmp/cat-vs-food/screenshot.jpg
     # ./lib/immagine/service.rb:88:in `generate_video_screenshot'
     # ./lib/immagine/service.rb:72:in `block in <class:Service>'
     # ./spec/immagine/service_spec.rb:486:in `block (4 levels) in <top (required)>'
```

if FFMPEG library is not installed on the system. 

We probably need to make this optional.

### PR DESCRIPTION
**Pull request by lozette**
Fixes #55 

Add handling for errors if FFMPEG is not installed on a system - return a 412 and log error.

### CODE REVIEW

File: lib/immagine/service.rb [hunk 1]
```diff
@@ -81,18 +81,20 @@ def source_folder
...
         process_video(source_file, output_file)
 
-        FileUtils.cp(output_file, File.join(source_folder, dir, "#{filename}.jpg"))
+        source_file = check_and_copy_screenshot(output_file, dir, filename)
 
-        source_file = File.join(source_folder, dir, "#{filename}.jpg")
+        generate_image(format_code, source_file)
+      rescue Errno::ENOENT
+        log_error('404, video processing not supported.')
+        raise Sinatra::NotFound
```
Comment (ettomatic) [inline lib/immagine/service.rb]: Not sure if a 404 is the right response here.

Comment (dazoakley) [inline lib/immagine/service.rb]: Yeah, maybe something like a 412?

> 412 Precondition Failed
> The server does not meet one of the preconditions that the requester put on the request.

Comment (lozette) [inline lib/immagine/service.rb]: Good call 👍

**Comment by dazoakley** [comment]
Looks good to me 👍
